# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi



# Tmuxinator completions
if [ -f ~/.bin/tmuxinator.zsh ]; then
    source ~/.bin/tmuxinator.zsh
fi

fpath=(/usr/local/share/zsh-completions $fpath)

export COMP_KNOWN_HOSTS_WITH_HOSTFILE=""



# bindkey -v
# bindkey -M viins '\e.' insert-last-word
# bindkey "^R" history-incremental-search-backward
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


export HISTFILE=~/.zsh_history
export HISTSIZE=1000000000
export SAVEHIST=$HISTSIZE
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS

# Remap clear-screen since ^L is taken by tmux-vim
bindkey "^O" clear-screen
bindkey "^L" end-of-line

# Disable right prompt for lecture recording
# RPROMPT=

# Alt left/right moves words
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

# Alt up/down goes to beggining/end of line
bindkey "^[[1;3A" beginning-of-line
bindkey "^[[1;3B" end-of-line

if [ -f $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  if [ -f $HOME/.zsh_highlight ]; then
    source $HOME/.zsh_highlight
  fi
fi


# https://github.com/marlonrichert/zsh-autocomplete
# if [ -f $HOME/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh ]; then
#   source $HOME/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# fi


typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# conda setup
if [ -f ~/.conda_init ]; then
    source ~/.conda_init
fi

# Environment setup
if [ -f ~/.env ]; then
    source ~/.env
fi

# ALIASES
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

# tools
if [ -f ~/.tools ]; then
    source ~/.tools
fi

# private env variables
if [ -f ~/.env_private ]; then
    source ~/.env_private
fi
